### ISSUE TITLE
C++ code should not include <math.h>, but <cmath>

### ISSUE THREAD

**Issue by danfe** [ArsMasiuk/qvge#101]
`#include <math.h>` was added to `CUtils.cpp` in 2d085a5 which GCC might be fine with, but Clang does not like:
```
CUtils.cpp:185:20: error: no member named 'sqrt' in namespace 'std'
    float l = std::sqrt(v.x() * v.x() + v.y() * v.y());
```
Replacing it with `#include <cmath>` fixes this.

**Comment by ArsMasiuk** [comment]
should be working now. thank you!
