### ISSUE TITLE
Not compiled #1

### ISSUE THREAD

**Issue by tieugene** [ArsMasiuk/qvge#108]
Fedora 32, "CONFIG += USE_LOCAL_OGDF" disabled:

make[1]: *** Нет правила для сборки цели «Icons/Format-PDF.png», требуемой для «_generated/qrc_commonui.cpp».  Останов.
make: *** [Makefile:224: sub--mnt-shares-home-eugene-rpmbuild-BUILD-qvge-0-6-0-src-commonui-commonui-pro-make_first-ordered] Ошибка 2

**Comment by ArsMasiuk** [comment]
Fixed with the latest release assets (v0.6.0-1)
