### ISSUE TITLE
Bundled boost

### ISSUE THREAD

**Issue by tieugene** [ArsMasiuk/qvge#109]
Many Linux distros deprecate bundling existent shared libraries as 3rdparties sources.
There must be something like (*.pro):
PKGCONFIG += boost_graph

Can't test because of Issue #108

**Comment by ArsMasiuk** [comment]
I cannot understand the problem here, sorry.
Tested with Linux Mint 19 (64 bit), gcc version 7.5.0. 
It gets compiled & linked fine.

**Comment by tieugene** [comment]
Ok, you can include whole of Qt in your source. No problem.
But _right_ way is to use linking with external shared libraries.

**Comment by ArsMasiuk** [comment]
I think boost will be removed together with OGDF as well because it was thought to import DOT files only.
But GraphViz does its job quite well for now (Windows & Linux - ok).
