### ISSUE TITLE
*.dot no supported

### ISSUE THREAD

**Issue by tieugene** [ArsMasiuk/qvge#116]
Example:
```dot
digraph SD_HD0 {
 rankdir="TB";
 overlap="false";
 {
  node [shape="circle",style="filled",fillcolor="black"];
  start	[label=""];
 }
 {
  node	[shape="rectangle",style="rounded,filled",fillcolor="lightgrey"];
  n00	[label="New"];
  n01	[label="Accepted"];
  n02	[label="Completed"];
  n03	[label="Approved"];
 }
 start -> n00 [label="Create"];
 n00 -> n01 [label="Accept"];
 n01 -> n02 [label="Complete"];
 n02 -> n03 [label="Approve"];
 n02 -> n00 [label="Renew"];
 n03 -> n00 [label="Renew"];
}
```
![sample](https://user-images.githubusercontent.com/1522763/89650121-91d6fa80-d8ca-11ea-8ae8-446c11847a4f.png)

**Comment by ArsMasiuk** [comment]
![116](https://user-images.githubusercontent.com/19762856/90051422-f5509600-dcd7-11ea-8a69-e8c25db8e749.PNG)

**Comment by ArsMasiuk** [comment]
Looks like BGL importer cannot parse such a graph (it thinks that there are clusters??)

**Comment by tieugene** [comment]
> (it thinks that there are clusters??)

Cluster definition is ["subgraph ..."](https://www.graphviz.org/Gallery/directed/cluster.html).
This is just very simple graph.

**Comment by ArsMasiuk** [comment]
Final solution has to be integrated now.
It should allow to import (almost) all the dot files which are correctly processed by dot engine.
