### ISSUE TITLE
Crash while label editing

### ISSUE THREAD

**Issue by ArsMasiuk** [ArsMasiuk/qvge#123]
1. create a node.
2. double-click on it and drag & release somewhere to create 2nd node.
3. go to 1st node and double click on it.
4. Label editor should come up. Enter some text and press Enter, then Escape.
5. It should crash now 👎

**Comment by ArsMasiuk** [comment]
escape must be disabled globally.

**Comment by Manningham** [comment]
I ran into this, just trying qvge for the first time.

1. create a node
2. double click to edit label
3. type something and press escape to "Finish label editing" (according to the hotkeys panel)
4. crash
