### ISSUE TITLE
Typo in `Default Properties` menu

### ISSUE THREAD

**Issue by ntjess** [ArsMasiuk/qvge#125]
I imagine the spelling should be `Disc` but instead it shows as `Dics`:
![image](https://user-images.githubusercontent.com/23620506/100020883-93abc780-2dae-11eb-8a9a-c6c1dcde824b.png)

**Comment by ntjess** [comment]
See the following line of code: https://github.com/ArsMasiuk/qvge/blob/7dcdff779afb4a72d612584274ab8126e30b2a93/src/qvge/CNodeEditorScene.cpp#L356

**Comment by ArsMasiuk** [comment]
good eye, thank you!
fixed now.
