### ISSUE TITLE
Build error in trunk

### ISSUE THREAD

**Issue by gns48** [ArsMasiuk/qvge#139]
Build error in trunk:

CImportExportUIController.cpp: In member function ‘bool CImportExportUIController::loadFromFile(const QString&, const QString&, CEditorScene&, QString*)’:
CImportExportUIController.cpp:263:50: error: cannot convert ‘CEditorScene’ to ‘CNodeEditorScene&’
  263 |         return (COGDFLayout::loadGraph(fileName, scene, lastError));
      |                                                  ^~~~~
      |                                                  |
      |                                                  CEditorScene
In file included from CImportExportUIController.cpp:17:
../../src/commonui/ogdf/COGDFLayout.h:32:70: note:   initializing argument 2 of ‘static bool COGDFLayout::loadGraph(const QString&, CNodeEditorScene&, QString*)’
   32 |     static bool loadGraph(const QString &filename, CNodeEditorScene &scene, QString* lastError = nullptr);
      |                                                    ~~~~~~~~~~~~~~~~~~^~~~~
Ubuntu 20.04.1 LTS
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
QT 5.12.8
Build with OGDF and boost

**Comment by danfe** [comment]
This had been already reported as #130.

**Comment by ArsMasiuk** [comment]
Fixed for 0.7.dev
