### ISSUE TITLE
.dot files not viewing

### ISSUE THREAD

**Issue by abukmail** [ArsMasiuk/qvge#157]
Hi, If I save a file as a .dot instead of .xgr I am unable to load it into QVGE. I drew a graph and saved it as .dot and when I open it I only get a very small canvas. Is there a way to convert the .dot to .xgr? 

Thank you,

**Comment by Tanami** [comment]
when I tried to open a .dot file on 4427a0c74dadb159e9f48724eae1ac24efcc7df2 it immediately segfaults

**Comment by ArsMasiuk** [comment]
hello,
thanks for the feedbacks!
could you please attach files which lead to the issue?

**Comment by Tanami** [comment]
```
digraph people {
rankdir=RL
api[label="api.example.com/v1/getProducts"]
fetch[label="fetch/ingest"]
fetch -> api [label="parameters:\n- modifiedBefore\n- pageNo\n- etc"]
}
```

**Comment by Tanami** [comment]
unfortunately I can't find the .dot file that was crashing before, sorry! I am pretty sure it was using record shape nodes though

**Comment by ArsMasiuk** [comment]
ok, the segfault hopefully has been fixed with 0.7.

The graph I've tried recently seems to work (also with 0.7 on Windows):

digraph people {
rankdir=RL
api[label="api.example.com/v1/getProducts"]
fetch[label="fetch/ingest"]
fetch -> api [label="parameters:\n- modifiedBefore\n- pageNo\n- etc"]
}

**Comment by ArsMasiuk** [comment]
may I close it already?

**Comment by Tanami** [comment]
go ahead! it looks fine now
