### ISSUE TITLE
support to export text file for further processing?

### ISSUE THREAD

**Issue by chensterliu** [ArsMasiuk/qvge#161]
Hello,
looks a fancy tool. I'm just curious if qvge supports exporting the edited graph to any text file (dot/json), so that any other machine without qvge can process the content.

**Comment by ArsMasiuk** [comment]
Hello,
Sure You can save a graph as graphml for example, this is a text format
too.

chen ***@***.***> schrieb am Fr., 8. Apr. 2022, 15:46:

**Comment by chensterliu** [comment]
Thanks for the quick reply. There should be some tools able to convert graphml to json/dot. Is it possible to directly export these 2 formats from qvge?

**Comment by ArsMasiuk** [comment]
Well, dot Export is supported but with some limitations.
No json support for now , sorry :(

chen ***@***.***> schrieb am Fr., 8. Apr. 2022, 16:36:

**Comment by chensterliu** [comment]
Still good to know the current export capability. Thanks, ArsMasluk.
