### ISSUE TITLE
Comple Error withi Qt 5.15.2 based with MSVC 2019 32

### ISSUE THREAD

**Issue by KnightZhao** [ArsMasiuk/qvge#165]
I'am new to the project ,and have error as follows :
qvgeui.lib(CPlatformWin32.obj) : error LNK2019: Unresolved external symbols  __imp__RegCloseKey@4，functions "private: static bool __cdecl
 CPlatformWin32::SetHkcrUserRegKey(class QString,class QString const &,class QString const &)"
 (?SetHkcrUserRegKey@CPlatformWin32@@CA_NVQString@@ABV2@1@Z) us this symbols
![error](https://user-images.githubusercontent.com/82133853/200164640-23a7bce5-ff56-477e-aa72-fe95ff85d600.PNG)

  looking forward to  having anyone to resolve the problem

**Comment by fredricj** [comment]
This should be fixed by #169

**Comment by WYZ1780** [comment]
你用的是哪个版本，我用 0.6.3分支，除了重新指定 VS 工具集 直接就编译通过了。编译环境是QT5.15 + VS2022 amd64。
![微信图片_20230309195051](https://user-images.githubusercontent.com/35841685/224014906-df17d8f8-fb34-4000-a3ed-0ac9a14eb2db.png)

**Comment by ArsMasiuk** [comment]
Hi, have you tried to build v.0.7.dev? does it work for you?
