### ISSUE TITLE
Crash on Windows when looading a dot file

### ISSUE THREAD

**Issue by vricosti** [ArsMasiuk/qvge#171]
Hi,
When I try to load a dot file (see attachment) with qvge (qvge-0.6.3-portable-64bit.zip) it crashes on Windows but it works on linux.
[qvge_crash-obf.dot.txt](https://github.com/ArsMasiuk/qvge/files/11859596/qvge_crash-obf.dot.txt)

**Comment by ArsMasiuk** [comment]
Hi, can you build v.0.7? Is it crashing as well?

**Comment by ArsMasiuk** [comment]
Should have been fixed in 0.7 already.
