### ISSUE TITLE
How to create edges?

### ISSUE THREAD

**Issue by holgerbrandl** [ArsMasiuk/qvge#176]
Hi, thanks for this nice app. Double-click creates a node. But how can I draw an edge between 2 nodes? Does this require a port or should it work without? The "Quick Help" does not indicate how to create edges.

**Comment by ArsMasiuk** [comment]
Hi!
Thanks for using the app!
Just double click a beginning node and, not releasing mouse button, drag
onto ending node and release there. An edge between the nodes should be
created.
Hope this helps.
Regards
Arseniy

Holger Brandl ***@***.***> schrieb am Sa., 20. Jan. 2024,
18:48:

**Comment by holgerbrandl** [comment]
Perfect thanks. I think I struggled with the wording in the  "Quick Help", which indicates that double click and drag creates a _node_ but not necessarily just an edge to an existing node.
