### ISSUE TITLE
Number of shapes

### ISSUE THREAD

**Issue by weed** [ArsMasiuk/qvge#38]
Individually, I need only the circle shape. I like more simple. To tell the truth, I have looked for the most simple graph editor for a long time and I feel that I found out just now.
![g__my drive_office_190331_2018 12 23 holomagnet5 gexf - qt visual graph editor 0 5 1 64bit 2018-12-23 05 09 45](https://user-images.githubusercontent.com/129954/50378246-0d8e2000-0671-11e9-9225-4af682d6ab7d.png)

**Comment by ArsMasiuk** [comment]
Thank you for this comment, it is really nice to hear that this software is usable :) could you probably tell me for which purposes you are going to use it? I mean which kind of graphs, file formats and so on, so I could than focus myself on development of more usable features.

**Comment by weed** [comment]
This software is already usable!

This figure is the structure of my Unity project. The way to develop Unity project is somehow different from other normal projects. In addition, I wanted to look through the whole project and rearrange it freely.

File format is default.

(To tell the truth, I'm thinking about the number of shapes. Maybe a rectangle is necessary.)

![20181223 holomagnet5structure](https://user-images.githubusercontent.com/129954/50466657-394b3600-09e2-11e9-8f09-99ccb7570ce7.jpg)

**Comment by ArsMasiuk** [comment]
For now, a predefined set of basic shapes is supported. It is intended to be compatible with the most of popular open graph file formats (gexf, graphml, gml). Maybe the set will be extended in the future for some kind of customized shapes, but you can already use any of already defined ones.

**Comment by ArsMasiuk** [comment]
For now, a predefined set of basic shapes is supported. It is intended to be compatible with the most of popular open graph file formats (gexf, graphml, gml). Maybe the set will be extended in the future for some kind of customized shapes, but you can already use any of already defined ones.

**Comment by weed** [comment]
What I mean is that the number of shapes might be too many for beginner, but I won't hold on this. Maybe a pallet of shapes which is able to customize might be better.

**Comment by weed** [comment]
Maybe I should say following.

>I won't hold on **to** this

I'm sorry for my poor English.

**Comment by weed** [comment]
The canvas has expanded today either. This is very useful because wherever I can begin drawing any kind of graph without changing tab or something like that.
<img width="2111" alt="2018 12 23 holomagnet5" src="https://user-images.githubusercontent.com/129954/50546365-18951180-0c6a-11e9-98f4-63961dc7e203.png">

**Comment by ArsMasiuk** [comment]
Do you mean the ability to have more graphs on the same canvas? Well, the application internally threats all the separate drawing as parts of a single graph. There is no support of subgraphs at the moment, however such a feature would be great to implement as well. I will schedule this for some future release.

**Comment by weed** [comment]
Thank you for considering, but I feel that I also have to learn how to use it called graph tool. I have used QVGE as a draw tool so far, and of course it is very useful, but I should know more. However, I haven't decided to used any other graph tools (I tried more that five tools). Because there are a lot of stencils on the interface, complicated way to connect each object, complicated interface which is hard to understand usage, they don't focus to the essence of graph but the appearance and just I want to do is to concentrate to draw simple graph enough to express network.

**Comment by weed** [comment]
Because of the simplicity, there is infinite variety of usage. We aren't forced to draw some typical type of figure. For example, I can express the class figure and the activity figure in the same one canvas. That is very useful!
![2019 1 6 holomagnet5](https://user-images.githubusercontent.com/129954/50733522-6c57ab80-11d2-11e9-80c1-f7ec730143ad.jpg)

**Comment by ArsMasiuk** [comment]
I agree, it can be closed for now. Thanks for sharing the sheet!
