### ISSUE TITLE
Canvas border line remains

### ISSUE THREAD

**Issue by tatsuro-ueda** [ArsMasiuk/qvge#42]
That occur when a canvas extends but the line disappears in a second

**Comment by ArsMasiuk** [comment]
Could you please explain what do you mean exactly... ?

**Comment by ArsMasiuk** [comment]
Could you please attach the file as well? This would be very helpful for me to track the issue down, thanks!

**Comment by ArsMasiuk** [comment]
Looks like an viewport update glitch anyway... Qt bug so to say.

**Comment by ArsMasiuk** [comment]
cannot reproduce it anymore.
