### ISSUE TITLE
"Show ID" in "View" menu

### ISSUE THREAD

**Issue by weed** [ArsMasiuk/qvge#47]
I'd like to hide IDs

**Comment by ArsMasiuk** [comment]
Hello,
This feature must be available since 0.5.0.
Which version of qvge do you use?

**Comment by weed** [comment]
Hello, I use 0.5.1. Do you mean "show labels"? I'd like to show not IDs but text label.

**Comment by weed** [comment]
It's because the same IDs aren't permitted. Of course that is right, but at least in my current graph, there are some objects with the same name.

**Comment by weed** [comment]
Anyway, I love this application. It's user experience is very good. It's because how to operate is sophisticated so intuitive and very simple. Because of that, it's easy to begin using. A user can entirely concentrate to a essence of content the whole time. Because of simpleness, the content is not noisy and easy to understand, and usable much generally to design, refactor and output a structure such as a organization, a software, logic, routes and all other relationships without learning usage separately. Thank you!

**Comment by weed** [comment]
It seems to me that my development have become more efficient after when I began using QVGE. This is much more useful than UML, because that I don't have to change sheets and to remember several usages and I can draw graphs swiftly. Yes this is useful!

**Comment by ArsMasiuk** [comment]
Sounds great!
Btw, what do you think about the following use-case:

- instead of using separate on/off switches for the labels and ids, I will introduce a global policy for item labels: Hidden/Always visible/Visible if no overlap (like for now);

- there come two separate switches: "Show Node IDs" and "Show Edge IDs" which will be active only if labels are allowed.

**Comment by weed** [comment]
In addition, I think that to double click to edit label is nice idea because the operation costs little length of time!
