### ISSUE TITLE
Urgent: Panes disappeared

### ISSUE THREAD

**Issue by weed** [ArsMasiuk/qvge#52]
I clicked "x" icon on the left and right pane to hide them. However, I couldn't find how to show again. 

I examined the xml file but I couldn't find such item. I uninstalled the app and reinstall the app, but the same problem occurred. I'd like to know how to avoid this problem.

![_ g__my drive_office_190331_2018 12 23 holomagnet5 gexf - qt visual graph editor 0 5 1 64bit 2018-12-31 06 58 26](https://user-images.githubusercontent.com/129954/50551811-bb7d7800-0cca-11e9-8f3f-6ccf8280e42a.png)

**Comment by ArsMasiuk** [comment]
You should right-click on any toolbar, and you will see a menu with all the toolbars and panels of the application. This is a "standard Qt-way" to manage them, but I agree that it is quite counter-intuitive.

**Comment by weed** [comment]
Oh I get it. I'm much relieved. Thank you! It's 7 am here. I can begin my work because of your help.

**Comment by ArsMasiuk** [comment]
So between us are 8 hours difference... Time to say Happy New year :)

And I think I will add a panels submenu to make a user easier to restore closed windows...

**Comment by ArsMasiuk** [comment]
Thank you! May you have a successful year 2019, too!
Btw which version do you use (windows, 32 bit or 64 bit)? I'd like to put an intermediate binary so that you could continue with it instead of waiting for an "official release"

**Comment by weed** [comment]
Thank you very much. Yes, I'm using 64-bit Windows, so I can use that. I'm outside now, but I'm looking forward to use that!

**Comment by weed** [comment]
My canvas is expanding still now!
<img width="3674" alt="2018 12 23 holomagnet5" src="https://user-images.githubusercontent.com/129954/50621153-68642900-0f47-11e9-9e3a-09db838cc874.png">

**Comment by weed** [comment]
Yes, I changed my idea that only one shape is good. Sorry and thank you.

**Comment by weed** [comment]
I just tried 0.5.2 preview now. It looks to work much better and easier to operate. I'm going to use this for a while. Thank you!

Before:
![_ g__my drive_office_190331_2018 12 23 holomagnet5 gexf - qt visual graph editor 0 5 2-preview 64bit 2019-01-05 19 45 25](https://user-images.githubusercontent.com/129954/50723568-eb8da680-1122-11e9-99ca-dc111560645f.png)

After:
![_ g__my drive_office_190331_2018 12 23 holomagnet5 gexf - qt visual graph editor 0 5 2-preview 64bit 2019-01-05 19 45 45](https://user-images.githubusercontent.com/129954/50723572-f21c1e00-1122-11e9-8a7a-f18513841da3.png)

It became more simple!

**Comment by weed** [comment]
I suggest to close this issue.
