### ISSUE TITLE
Portable distribution

### ISSUE THREAD

**Issue by DJuego** [ArsMasiuk/qvge#54]
Hi again! 

Would it be possible to distribute **qvge** without installer for Windows? Ready to run! Only binaries... 

I think it's a pretty desirable feature in small, elegant, nifty and beautiful tools.

Thank you!

DJuego

**Comment by ArsMasiuk** [comment]
Hi!
I think this is reasonable. I would add this feature since some upcoming release, thank you for the idea!

**Comment by DJuego** [comment]
Thank you for your understanding @ArsMasiuk!

DJuego

**Comment by ArsMasiuk** [comment]
done for Windows in 0.6

**Comment by DJuego** [comment]
Thank you very much!  I'll look forward to the release!

DJuego

**Comment by ArsMasiuk** [comment]
Sorry that it has taken so much time..  and thanks for the patience :)
Btw. may I ask which features do you find usable or what part of the app
could be improved somehow?

**Comment by DJuego** [comment]
Good things are sometimes made to wait. 
When I have something concrete to feed you back to, I'll do it right away.  Don't have any doubts about that. :-)

Thank you again, @ArsMasiuk .

DJuego

P.S:  If you like, I'll close the thread when 0.6 is released.

**Comment by DJuego** [comment]
You've honored your promise. This issue has been resolved. Thank you very much for this! 

If I find out anything new I'll let you know. Sure! :-)

DJuego
