### ISSUE TITLE
Application become down when I deleted a node

### ISSUE THREAD

**Issue by tatsuro-ueda** [ArsMasiuk/qvge#55]
Application become down when I deleted a node. I cannot reproduce the situation because my work from when I saved my file is lost. I'm sorry that I have to participate my family's dinner now so that I cannot explain more, but I think there is no more information about this.

![microsoft visual c runtime library 2019-01-06 18 10 20](https://user-images.githubusercontent.com/129954/50734215-353bc700-11df-11e9-8060-518e2e96356c.png)

**Comment by weed** [comment]
Don't worry. I'm accepting the risk to use the preview version. My roll as a contributor is tester. However.... the work I lost was... oh, never mind. It's all right.

**Comment by weed** [comment]
I just recovered my work and even improved!

**Comment by weed** [comment]
Maybe I'd better not to post this issue here. I'm sorry if you feel ill.

**Comment by weed** [comment]
Thank you for considering measures to meet the situation.

However, in my opinion, you don't have to hurry to implement those functions if implementation is not easy or depends on the evolving application architecture. If anything, though I don't know this is possible, I suggest to add function to dump memory. That might let the development avoidable from difficult problems to solve.
