### ISSUE TITLE
Add recent files view

### ISSUE THREAD

**Issue by ArsMasiuk** [ArsMasiuk/qvge#59]
A panel to quickly select recently used files

**Comment by ArsMasiuk** [comment]
When the app starts, there is a huge blank space in the middle. I thought about something like startup screen with some common actions plus recently opened files as a detailed list. So alike qt creator.

**Comment by weed** [comment]
Do you mean like this?
![qtcreator-welcome-session](https://user-images.githubusercontent.com/129954/51081092-d9b39100-172a-11e9-819e-1e269a9d3c5d.png)

**Comment by ArsMasiuk** [comment]
Yes, something like this

**Comment by weed** [comment]
I think it's nice
