### ISSUE TITLE
Save/export only the topology.

### ISSUE THREAD

**Issue by DJuego** [ArsMasiuk/qvge#63]
Sometimes it is desirable to rip everything that has nothing to do with the graph. For example metainformation for visual presentation.

For instance; for:

```
"A" -> "C" [id = "E2"
,weight = "1"
,penwidth = "1"
,xlabel = ""
,"color" = "#000000"
,"style" = "solid"
];
```
We only need:

```
"A" -> "C"
```

DJuego

**Comment by ArsMasiuk** [comment]
Will come with the next release.
