### ISSUE TITLE
Application crashes when used

### ISSUE THREAD

**Issue by almereyda** [ArsMasiuk/qvge#67]
After compiling with `qt5-devel` on Fedora 29 and by using `qmake-qt5 -r` before invoking the `make` step, the application crashes semi-randomly.

It can be reproduced to terminate the process by clicking on the Window item in the menu bar.

Editing the graph also quits the application sometimes.

Which would be a way to debug this situation?

**Comment by ArsMasiuk** [comment]
Could you please tell which Qt version and compiler/platform do you use?
