### ISSUE TITLE
Seems to ignore PREFIX=/usr and INSTALL_ROOT=appdir

### ISSUE THREAD

**Issue by probonopd** [ArsMasiuk/qvge#69]
I am trying to build QVGE so that it has

```
./appdir/usr/bin/qvge
./appdir/usr/share/applications/qvge.desktop
./appdir/usr/lib/...
```

However, the following does not produce the intended result:

```
cd ./src
qmake CONFIG+=release PREFIX=/usr
make -j$(nproc)
make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
```

What do I need to do?

Build log:
https://api.travis-ci.com/v3/job/199486605/log.txt

Travis CI build script:
https://github.com/probonopd/qvge/blob/patch-1/.travis.yml

**Comment by ArsMasiuk** [comment]
hi,
I'm not sure that there's QVGE issue.
It should work with the default Qt build system, i.e. qmake + make.
And please tell what do you mean under "intended result"? where is the problem?

**Comment by probonopd** [comment]
> It should work with the default Qt build system, i.e. qmake + make.

This is what I am using:
https://github.com/probonopd/qvge/blob/d28b57bba6e7d6bcdc71da7db2bb11f201bcceed/.travis.yml#L16-L18

> And please tell what do you mean under "intended result"? 

```
./appdir/usr/bin/qvge
./appdir/usr/share/applications/qvge.desktop
./appdir/usr/lib/...
```

> where is the problem?

It does not produce that.

**Comment by ArsMasiuk** [comment]
will be done for 0.6.

**Comment by ArsMasiuk** [comment]
done, should work for 0.6

**Comment by probonopd** [comment]
Thank you very much. Now I am running into:

```
/usr/bin/ld: cannot find -lcommonui

/usr/bin/ld: cannot find -lqvge
```

Is there anything special I need to do?

**Comment by ArsMasiuk** [comment]
well, I've (hopefully, because that with PREFIX is actually not QMake-default feature) fixed the issue for branch 0.6.
Are you sure you are checking out this branch and not master one?

**Comment by probonopd** [comment]
> Are you sure you are checking out this branch and not master one?

My bad!

**Comment by probonopd** [comment]
Actually with 0.6 I am getting more errors:

```
/usr/bin/ld: cannot find -lcommonui

/usr/bin/ld: cannot find -lqvge

/usr/bin/ld: cannot find -lqvgeio

/usr/bin/ld: cannot find -lqtpropertybrowser

/usr/bin/ld: cannot find -lqsint-widgets

/usr/bin/ld: cannot find -logdf-2020

collect2: error: ld returned 1 exit status

make[1]: *** [../bin/qvgeapp] Error 1
```

https://travis-ci.com/github/probonopd/qvge/builds/173364209#L1749-L1754

Probably I am missing something.

**Comment by ArsMasiuk** [comment]
Did you run qmake -r from src directory?

**Comment by probonopd** [comment]
Been running

https://github.com/probonopd/qvge/blob/cfc1fb2ad4ff328ad2a3afcbdc1efb5020b19351/.travis.yml#L16

Is it wrong?

**Comment by ArsMasiuk** [comment]
cd src
qmake -r PREFIX=/usr
make
make install INSTALL_ROOT=appdir

Works for me.
