### ISSUE TITLE
How to get dependencies?

### ISSUE THREAD

**Issue by chazanov** [ArsMasiuk/qvge#70]
The build fails for me, probably due to missing libraries:
```
g++ -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o ../bin/qvgeapp main.o qvgeMainWindow.o qrc_qvgeapp.o moc_qvgeMainWindow.o   -L/home/papa/aur/_graphdb/qvge/src/qvge/src/qvgeapp/../lib -lcommonui -lqvge -lqvgeio -lqtpropertybrowser -lqsint-widgets -logdf -lQt5X11Extras -lX11 /usr/lib/libQt5OpenGL.so /usr/lib/libQt5PrintSupport.so /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Xml.so /usr/lib/libQt5Network.so /usr/lib/libQt5Core.so /usr/lib/libGL.so -lpthread   
/usr/bin/ld: cannot find -lcommonui
/usr/bin/ld: cannot find -lqvge
/usr/bin/ld: cannot find -lqvgeio
/usr/bin/ld: cannot find -lqtpropertybrowser
/usr/bin/ld: cannot find -lqsint-widgets
/usr/bin/ld: cannot find -logdf
```
I've just found ogdf, but where may I get
- commonui
- qtpropertybrowser
- qsint-widgets
-
from?

**Comment by ArsMasiuk** [comment]
Hello,
All these libraries should be built before the main application (they are under src/3rdParty).
You have to call "qmake -r qvgeapp.pro" out of src directory first, then make.

**Comment by chazanov** [comment]
Oh, thanks.

**Comment by sanaris** [comment]
@ArsMasiuk How do I build it when I already have libogdf installed system-wide? Can I skip somehow and not mess with different versions "my" and "supplied"??
