### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by sanaris** [ArsMasiuk/qvge#84]
Version 0.6.x does not build.

No matching for AttrInfo::AttrInfo() from CNodeEditorScene.cpp:192

[build.log](https://github.com/ArsMasiuk/qvge/files/4438986/build.log)

QMake 3.1
QT 5.14.2
Make 4.2.1

Let me know is you need full build logs.

**Comment by ArsMasiuk** [comment]
thank you for the information, I'll check it ASAP

**Comment by ArsMasiuk** [comment]
fixed now. C++14 standard forced.
