### ISSUE TITLE
ogdf integration

### ISSUE THREAD

**Issue by gedalia** [ArsMasiuk/qvge#85]
I'm trying to build this for the first time, and I'm not that familiar with qmake. ogdf seems to be cmake based and I'm not sure where ogdf.pro is supposed to come from.

**Comment by ArsMasiuk** [comment]
There is a local copy of ogdf shipped with the qvge app. You don't have to build ogdf separately. Just use qmake+make commands as it is described in the main page. All the 3rdparties should be compiled automatically then.
