### ISSUE TITLE
Linux desktop integration absent

### ISSUE THREAD

**Issue by tieugene** [ArsMasiuk/qvge#91]
Applications must install into /usr/share/...:
- icon[s] into .../pixmaps/ and/or .../icons/...
- *.desktop into .../applications/ ([RTFM](https://standards.freedesktop.org/desktop-entry-spec/latest/))
- *.xml into .../appdata/ and/or .../metainfo/ ([RTFM](https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/))

**Comment by ArsMasiuk** [comment]
#69 - it was mentioned already I think.

**Comment by ArsMasiuk** [comment]
done for 0.6
