### ISSUE TITLE
Qt5 X11Extras not checked on making Makefile stage (qmake)

### ISSUE THREAD

**Issue by tieugene** [ArsMasiuk/qvge#92]
subj

**Comment by ArsMasiuk** [comment]
Could you please explain the issue more detailed? I cannot get what is wrong :(

**Comment by tieugene** [comment]
Good way when qmake-qt produces something like "Can't find ... library".
But now it produce Makefile without any warning/error.
And I see that Qt5X11Extras absent in the middle of compilation.
Not before - in the middle.

**Comment by ArsMasiuk** [comment]
Well, generation of Makefile is up to qmake tool itself.
Normally Qt5X11Extras should be a part of default Qt installation. If not, then I would consider this to be an issue with the particular Qt distribution.

**Comment by tieugene** [comment]
Normally Qt5X11Extras is installed by default in "Normal OS" &trade; (don't know where to download it).
I use "Fedora Linux", where qt5-qtx11extras-devel is separate package.
Another "innormal" Linux distributions - Debian, Ubuntu - use libqt5x11extras5-dev instead.

**Comment by danfe** [comment]
It could be that dependency on `x11extras` is not specified correctly.  You may want to try patching `app.pri` like this:
```diff
 unix{
     !haiku{
-        LIBS += -lQt5X11Extras -lX11
+        QT += x11extras
+        LIBS += -lX11
     }
```

**Comment by ArsMasiuk** [comment]
thank you *danfe*, that was it I hope :)
